spring:
  application:
    name: ead-notification
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: configs-server
      username: guestcs
      password: guestcs
