server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      routes:
        - id: ead-course
          uri: lb://EAD-COURSE
          predicates:
            - Path=/ms-ead/course/**
          filters:
            - RewritePath=/ms-ead/course(?<segment>/?.*), $\{segment}
        - id: ead-authuser
          uri: lb://EAD-AUTHUSER
          predicates:
            - Path=/ms-ead/authuser/**
          filters:
            - RewritePath=/ms-ead/authuser(?<segment>/?.*), $\{segment}

logging:
  level:
    br.com.gateway.*: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-}]"
