server:
  port: 0

spring:
  application:
    name: ead-authuser
  datasource:
    url: jdbc:mysql://localhost:3306/ead-authuser?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.ead.authuser: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-}]"

ead:
  api:
    url:
      course: http://ead-course
  broker:
    exchange:
      userEvent: ead.userevent

eureka:
  instance:
    instance-id:
      ${spring.application.name}:${random.int}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      retryInstance:
        max-attempts: 3
        wait-duration: 5s
