server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead-authuser?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    com.ead.authuser: debug

ead:
  api:
    url:
      course: 'http://localhost:8082'
