server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead-course?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
