server:
  port: 0

spring:
  application:
    name: ead-course
  datasource:
    url: jdbc:mysql://localhost:3306/ead-course?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
#  mvc:
#    problemdetails:
#      enabled: true

ead:
  api:
    course:
      url: http://ead-authuser

eureka:
  instance:
    instance-id:
      ${spring.application.name}:${random.int}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-}]"
