server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghmiyoshi/configs-server-yml
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
